// ─── MASTER DATA: Pencils, Papers, Shop Items ─────────────────────────────────
// Single source of truth for all Artgez supply data.
// Frontend + Backend both reference this structure.

export const PENCILS_DATA = [
    {
        id: '4h', label: '4H', brand: 'Faber-Castell', price: 49, priceStr: '₹49',
        hardness: 0.95, darkness: 0.12, smudge: 0.04, opacity: 0.2, size: 0.7, color: '#bbc5cf',
        desc: 'Very hard, razor-light marks for technical precision.',
        bestFor: ['Technical drawing', 'Construction lines', 'Architecture sketches'],
        category: 'graphite',
        tip: 'Perfect for initial light sketch guides before committing with darker pencils.',
        affiliateUrl: 'https://www.amazon.in/s?k=faber+castell+4h+pencil',
    },
    {
        id: '2h', label: '2H', brand: 'Faber-Castell', price: 49, priceStr: '₹49',
        hardness: 0.75, darkness: 0.28, smudge: 0.1, opacity: 0.35, size: 1.0, color: '#9aaab8',
        desc: 'Hard and precise — ideal for clean outlines.',
        bestFor: ['Outlines', 'Fine details', 'Illustration guides'],
        category: 'graphite',
        tip: 'Use this after a 4H sketch to define your lines before shading.',
        affiliateUrl: 'https://www.amazon.in/s?k=faber+castell+2h+pencil',
    },
    {
        id: 'hb', label: 'HB', brand: 'Staedtler', price: 35, priceStr: '₹35',
        hardness: 0.5, darkness: 0.5, smudge: 0.35, opacity: 0.55, size: 1.5, color: '#555f70',
        desc: 'Perfect all-rounder. Every artist should own one.',
        bestFor: ['General sketching', 'Studies', 'Everyday drawing'],
        category: 'graphite',
        tip: 'The HB is the "middle child" — not too hard, not too soft. Best starting pencil.',
        affiliateUrl: 'https://www.amazon.in/s?k=staedtler+hb+pencil',
    },
    {
        id: '2b', label: '2B', brand: 'Faber-Castell', price: 55, priceStr: '₹55',
        hardness: 0.35, darkness: 0.72, smudge: 0.55, opacity: 0.78, size: 2.2, color: '#2a2e40',
        desc: 'Soft and dark — the go-to for expressive shading.',
        bestFor: ['Shading', 'Portraits', 'Expressive marks'],
        category: 'graphite',
        tip: 'Most-loved pencil for portrait artists. Great middle ground between control and expressiveness.',
        affiliateUrl: 'https://www.amazon.in/s?k=faber+castell+2b+pencil',
    },
    {
        id: '4b', label: '4B', brand: 'Faber-Castell', price: 65, priceStr: '₹65',
        hardness: 0.2, darkness: 0.87, smudge: 0.78, opacity: 0.9, size: 3.2, color: '#181a26',
        desc: 'Very dark and rich for dramatic shadow work.',
        bestFor: ['Deep shadows', 'Figure drawing', 'Bold strokes'],
        category: 'graphite',
        tip: 'Hold lightly for soft gradients. Press hard for inky blacks.',
        affiliateUrl: 'https://www.amazon.in/s?k=faber+castell+4b+pencil',
    },
    {
        id: '6b', label: '6B', brand: 'Staedtler', price: 75, priceStr: '₹75',
        hardness: 0.08, darkness: 0.97, smudge: 0.92, opacity: 0.96, size: 4.8, color: '#0c0d18',
        desc: 'Blackest graphite — velvety, powdery, dramatic.',
        bestFor: ['Rich blacks', 'Gesture drawing', 'Large areas'],
        category: 'graphite',
        tip: 'Warning: very messy. Keep a tissue nearby for smudging and blending.',
        affiliateUrl: 'https://www.amazon.in/s?k=staedtler+6b+pencil',
    },
    {
        id: 'ch', label: 'Charcoal', brand: 'Camlin', price: 99, priceStr: '₹99',
        hardness: 0.12, darkness: 0.93, smudge: 0.97, opacity: 0.72, size: 6.5, color: '#1c1c1c',
        desc: 'Powdery and smudgeable — gestural and expressive.',
        bestFor: ['Life drawing', 'Bold gestures', 'Portrait work'],
        category: 'charcoal',
        tip: 'Use your finger or a tortillon to blend. Erasable with a kneaded eraser.',
        affiliateUrl: 'https://www.amazon.in/s?k=camlin+charcoal+pencil',
    },
    {
        id: 'ink', label: 'Ink Pen', brand: 'Sakura', price: 149, priceStr: '₹149',
        hardness: 1.0, darkness: 1.0, smudge: 0.0, opacity: 1.0, size: 1.2, color: '#04040e',
        desc: 'Permanent, crisp, zero smudge. Perfect for final inking.',
        bestFor: ['Inking', 'Comic art', 'Final linework'],
        category: 'ink',
        tip: 'Always sketch in pencil first. Ink is permanent — plan before you commit.',
        affiliateUrl: 'https://www.amazon.in/s?k=sakura+pigma+micron',
    },
    {
        id: 'bp', label: 'Brush Pen', brand: 'Pentel', price: 199, priceStr: '₹199',
        hardness: 0.4, darkness: 0.92, smudge: 0.0, opacity: 0.93, size: 3.8, color: '#0e0d1e',
        desc: 'Flexible tip for calligraphy and expressive inking.',
        bestFor: ['Calligraphy', 'Comics', 'Expressive inking'],
        category: 'ink',
        tip: 'Practice varying pressure — thin lines on light touch, thick strokes when you press down.',
        affiliateUrl: 'https://www.amazon.in/s?k=pentel+pocket+brush+pen',
    },
];

export const PAPERS_DATA = [
    {
        id: 'smooth', label: 'Smooth', brand: 'Fabriano', grain: 0, bg: '#fdfbf7',
        desc: 'Ultra-smooth surface, best for detail work and ink.',
        feel: 'Glass-like. Your pencil glides with almost no resistance.',
        bestFor: ['Technical drawing', 'Ink work', 'Fine detail'],
        priceRange: '₹150–₹500',
    },
    {
        id: 'rough', label: 'Rough', brand: 'Canson', grain: 0.62, bg: '#f4efe5',
        desc: 'Heavy tooth — excellent for charcoal and pastels.',
        feel: 'Gritty. The paper fights back — in a good way.',
        bestFor: ['Charcoal', 'Pastels', 'Expressive work'],
        priceRange: '₹200–₹600',
    },
    {
        id: 'newsprint', label: 'Newsprint', brand: 'Generic', grain: 0.28, bg: '#eee8d6',
        desc: 'Warm-toned, affordable. Great for practice.',
        feel: 'Slightly textured, warm off-white. Forgiving for practice.',
        bestFor: ['Practice', 'Gesture drawing', 'Warm-up sketches'],
        priceRange: '₹80–₹200',
    },
    {
        id: 'watercolor', label: 'Watercolor', brand: 'Fabriano', grain: 0.85, bg: '#f7f2ea',
        desc: 'Highly textured and absorbent.',
        feel: 'Very rough and bumpy. Pencil strokes break over the peaks.',
        bestFor: ['Watercolor pencils', 'Mixed media', 'Texture studies'],
        priceRange: '₹300–₹800',
    },
    {
        id: 'canvas', label: 'Canvas', brand: 'Generic', grain: 0.72, bg: '#f0e9da',
        desc: 'Coarse and gritty — gives a painterly feel.',
        feel: 'The coarsest option. Gives a painted, rough aesthetic.',
        bestFor: ['Experimental work', 'Oil pencils', 'Coarse shading'],
        priceRange: '₹200–₹700',
    },
    {
        id: 'kraft', label: 'Kraft', brand: 'Generic', grain: 0.22, bg: '#c9a87c',
        desc: 'Brown paper — warm tone, unique for white pencil highlights.',
        feel: 'Warm, earthy. Works beautifully with white charcoal for highlights.',
        bestFor: ['Toned paper drawings', 'White highlights', 'Unique aesthetic'],
        priceRange: '₹50–₹150',
    },
];

export const SHOP_DATA = [
    {
        id: 'fc-2b', name: 'Faber-Castell 2B Pencil', brand: 'Faber-Castell', type: 'Graphite',
        price: 55, priceStr: '₹55', rating: 4.8, reviews: 1240, pencilId: '2b', emoji: '✏️',
        desc: 'Best-selling graphite for shading and portrait work.',
        affiliateUrl: 'https://www.amazon.in/s?k=faber+castell+2b+pencil',
        inStock: true, isBestSeller: true,
    },
    {
        id: 'st-hb', name: 'Staedtler HB (12 pack)', brand: 'Staedtler', type: 'Graphite',
        price: 299, priceStr: '₹299', rating: 4.7, reviews: 890, pencilId: 'hb', emoji: '✏️',
        desc: 'A classroom staple. Reliable and consistent every time.',
        affiliateUrl: 'https://www.amazon.in/s?k=staedtler+hb+pencil+12',
        inStock: true, isBestSeller: false,
    },
    {
        id: 'fc-6b', name: 'Faber-Castell 6B Pencil', brand: 'Faber-Castell', type: 'Graphite',
        price: 75, priceStr: '₹75', rating: 4.9, reviews: 2100, pencilId: '6b', emoji: '✏️',
        desc: 'The darkest graphite you can get. Dramatic and velvety.',
        affiliateUrl: 'https://www.amazon.in/s?k=faber+castell+6b+pencil',
        inStock: true, isBestSeller: true,
    },
    {
        id: 'cam-ch', name: 'Camlin Charcoal Pencils', brand: 'Camlin', type: 'Charcoal',
        price: 99, priceStr: '₹99', rating: 4.6, reviews: 560, pencilId: 'ch', emoji: '🖤',
        desc: 'Smudgeable, powdery charcoal sticks for gestural art.',
        affiliateUrl: 'https://www.amazon.in/s?k=camlin+charcoal+pencil',
        inStock: true, isBestSeller: false,
    },
    {
        id: 'sk-ink', name: 'Sakura Pigma Micron 01', brand: 'Sakura', type: 'Ink',
        price: 149, priceStr: '₹149', rating: 4.9, reviews: 3400, pencilId: 'ink', emoji: '🖊️',
        desc: 'Industry standard for inking and comic art.',
        affiliateUrl: 'https://www.amazon.in/s?k=sakura+pigma+micron+01',
        inStock: true, isBestSeller: true,
    },
    {
        id: 'pen-bp', name: 'Pentel Pocket Brush Pen', brand: 'Pentel', type: 'Ink',
        price: 199, priceStr: '₹199', rating: 4.8, reviews: 780, pencilId: 'bp', emoji: '🖌️',
        desc: 'Flexible real-brush feel in a pen form.',
        affiliateUrl: 'https://www.amazon.in/s?k=pentel+pocket+brush+pen',
        inStock: true, isBestSeller: false,
    },
    {
        id: 'fab-sm', name: 'Fabriano Smooth Sketch A4', brand: 'Fabriano', type: 'Paper',
        price: 450, priceStr: '₹450', rating: 4.7, reviews: 430, pencilId: null, emoji: '📒',
        desc: 'Premium smooth surface for graphite and ink work.',
        affiliateUrl: 'https://www.amazon.in/s?k=fabriano+sketchbook+smooth',
        inStock: true, isBestSeller: false,
    },
    {
        id: 'can-ro', name: 'Canson Rough Pad A4', brand: 'Canson', type: 'Paper',
        price: 320, priceStr: '₹320', rating: 4.6, reviews: 290, pencilId: null, emoji: '📔',
        desc: 'Cold-press texture — perfect for charcoal and pastels.',
        affiliateUrl: 'https://www.amazon.in/s?k=canson+rough+paper+pad',
        inStock: true, isBestSeller: false,
    },
    {
        id: 'st-set', name: 'Staedtler Sketch Set 8pc', brand: 'Staedtler', type: 'Kit',
        price: 599, priceStr: '₹599', rating: 4.9, reviews: 1800, pencilId: null, emoji: '🎨',
        desc: 'Complete beginner kit: HB to 6B + charcoal + eraser.',
        affiliateUrl: 'https://www.amazon.in/s?k=staedtler+sketch+set',
        inStock: true, isBestSeller: true,
    },
];
